# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-analysis-app
  labels:
    app: stock-analysis
spec:
  replicas: 2
  selector:
    match_labels:
      app: stock-analysis
  template:
    metadata:
      labels:
        app: stock-analysis
    spec:
      containers:
      - name: stock-analysis-container
        # ğŸŒŸ CI/CD íŒŒì´í”„ë¼ì¸ì´ ì´ ê°’ì„ ì‹¤ì œ ECR ì´ë¯¸ì§€ URIì™€ SHA íƒœê·¸ë¡œ ëŒ€ì²´í•©ë‹ˆë‹¤. ğŸŒŸ
        image: <ECR_URL>/stock-analysis-eks-app:latest 
        ports:
        - containerPort: 8080
        resources: # ì˜¤í† ìŠ¤ì¼€ì¼ë§ í…ŒìŠ¤íŠ¸ë¥¼ ìœ„í•´ ë¦¬ì†ŒìŠ¤ ìš”ì²­ ì •ì˜
          requests:
            cpu: 100m
          limits:
            cpu: 200m